services:
  servidor-web:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: servidor-web
    ports:
      - "8080:8080"
    networks:
      - rede-comunicacao
    restart: unless-stopped

  cliente:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: cliente-requisicoes
    depends_on:
      - servidor-web
    networks:
      - rede-comunicacao
    restart: unless-stopped

networks:
  rede-comunicacao:
    driver: bridge